### PR TITLE
Add safe area support

### PR DESCRIPTION
**Pull request by dogo**
Add SnapKit+SafeArea extension

### CODE REVIEW

**Comment by DouglasMedeiros** [comment]
Time

**Comment by DouglasMedeiros** [comment]
Not pass

**Comment by DouglasMedeiros** [comment]
Accept

**Comment by DouglasMedeiros** [comment]
bigger

**Comment by DouglasMedeiros** [comment]
[approves](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbwWh_NcZS3IeyyN_P5z1ihSvFaX_1oj2Jfa_J8tkfBWlutAbbUw)!

**Comment by dogo** [comment]
Huahauahauahai eu to rindo muito

**Comment by DouglasMedeiros** [comment]
Finish

**Pull request merged**
